In [113]:
#Imports
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn

from data_manager import get_data


from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import RandomizedSearchCV



In [114]:
ds2, ds3 = get_data()
#print(ds2)
#print(ds3)

In [115]:
#Create X and y
X = np.array(ds3.drop(['target', 'NP_Cya_bio'], axis=1))
y = np.array(ds3['target'])
y_reg = np.array(ds3['NP_Cya_bio']) #for regression


In [116]:
#Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y_reg, test_size=0.20)

In [117]:
#Scale the X's
X_train = preprocessing.scale(X_train)
X_test = preprocessing.scale(X_test)

In [118]:
#Linear regression
model = linear_model.LinearRegression()
model.fit(X, y_reg)
print(model.score(X, y_reg))
print(model.coef_) # get theta coefficients (model params)


0.4331216573107976
[  453312.08223563  -818274.02190306 -1715702.92705677 22265050.0175068
  -263676.33980401 11993814.38669171 10201003.8236107    300020.02127503
  2706418.64463787]


In [119]:
#Try again using Bagrow's method?

In [123]:
#Logistic regression
# define the model
model = LogisticRegression(solver = "liblinear", penalty = 'l2')
# train the model
model.fit(X_train, y_train)

# make predictions using the trained model on unseen data
predicted = model.predict(X_test)

# measure the performance 
ac = accuracy_score(y_test,predicted)

# report the results 
print("Accuracy is: ",ac);

print ("Number of test samples = ",len(y_test))
confusion = metrics.confusion_matrix(y_test, predicted)
print(confusion)

/Users/mahaliaclark/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Accuracy is:  0.289198606271777
Number of test samples =  287
[[83  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 ...
 [ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


#### Things to try for logistic regression:
- ds2 vs ds3
- features scaled vs not
- use cross validation
- get performance summary with recall and ROC AUC and confusion matrix
- add polynomial features
- add regularization: try elastic net and/or Lasso (=L1?)
- use random search and cross validation to tune hyperparameters, find best model (specify scoring metric as recall/F1/AUC?):
    - C (inverse of regularization strength --> smaller value = more regularization)
    - solver (choice depends on choice of regularization)
    - penalty (form of regularization?)
    - l1_ratio: ratio between 0 and 1 passed for elasticnet